
---
language: node_js
node_js:
  - "4"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-1.13
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "npm config set spin false"
  - npm install -g npm@4
  - npm --version

install:
  - npm install
  - bower install

script:
  - npm run lint:js
  - if [ "${EMBER_TRY_SCENARIO}" = "ember-release" ]; then ember try:one $EMBER_TRY_SCENARIO; else ember try:one $EMBER_TRY_SCENARIO --skip-cleanup; fi

deploy:
  provider: heroku
  api_key:
    secure: JyCVhFlH+gDBkHoIivvBVNNIVuJSZT5jeFDHCBAhCMh2OsHCK99hlGtLJRjG6fPWwJ81jorUb14RDA5jxU/2VPeFvefelDqarkG3lWNUUnVtiFk2mDBuhYHW03P11btoixcg2NTr7cgNjARWEt4UbaZ1a0QkdzsmzhIbSjShrRk=
  app: ember-materialize-demo
  on:
    repo: mike-north/ember-cli-materialize
    condition: "$EMBER_TRY_SCENARIO = ember-release"
